services:

  php:
    build: ./backend
    container_name: sistema_comentarios_php
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - mysql
    networks:
      - comentarios_network


  mysql:
    image: mysql:8.0
    container_name: sistema_comentarios_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_comentarios
      MYSQL_USER: dennis
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - comentarios_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_comentarios_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: dennis
      PMA_PASSWORD: 123456
    depends_on:
      - mysql
    networks:
      - comentarios_network


networks:
  comentarios_network:


volumes:
  mysql_data: